// Code generated by MockGen. DO NOT EDIT.
// Source: consumer.go

// Package receiver is a generated GoMock package.
package receiver

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/agent/domain"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// HandleRawUpdate mocks base method.
func (m *MockService) HandleRawUpdate(ctx context.Context, rawUpdate domain.RawUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRawUpdate", ctx, rawUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleRawUpdate indicates an expected call of HandleRawUpdate.
func (mr *MockServiceMockRecorder) HandleRawUpdate(ctx, rawUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRawUpdate", reflect.TypeOf((*MockService)(nil).HandleRawUpdate), ctx, rawUpdate)
}
