// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/domain"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockStorage) AddLink(chatId int64, url string, tags []string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", chatId, url, tags)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockStorageMockRecorder) AddLink(chatId, url, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockStorage)(nil).AddLink), chatId, url, tags)
}

// ChatExists mocks base method.
func (m *MockStorage) ChatExists(chatId int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatExists", chatId)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ChatExists indicates an expected call of ChatExists.
func (mr *MockStorageMockRecorder) ChatExists(chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatExists", reflect.TypeOf((*MockStorage)(nil).ChatExists), chatId)
}

// DeleteChat mocks base method.
func (m *MockStorage) DeleteChat(chatId int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteChat", chatId)
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockStorageMockRecorder) DeleteChat(chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockStorage)(nil).DeleteChat), chatId)
}

// GetLinks mocks base method.
func (m *MockStorage) GetLinks(chatId int64) []domain.Link {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", chatId)
	ret0, _ := ret[0].([]domain.Link)
	return ret0
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockStorageMockRecorder) GetLinks(chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockStorage)(nil).GetLinks), chatId)
}

// RegisterChat mocks base method.
func (m *MockStorage) RegisterChat(chatId int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterChat", chatId)
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockStorageMockRecorder) RegisterChat(chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockStorage)(nil).RegisterChat), chatId)
}

// RemoveLink mocks base method.
func (m *MockStorage) RemoveLink(chatId int64, url string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", chatId, url)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockStorageMockRecorder) RemoveLink(chatId, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockStorage)(nil).RemoveLink), chatId, url)
}
