// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/domain"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockClient) Check(ctx context.Context, link domain.Link) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, link)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Check indicates an expected call of Check.
func (mr *MockClientMockRecorder) Check(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockClient)(nil).Check), ctx, link)
}

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// SendUpdate mocks base method.
func (m *MockNotifier) SendUpdate(ctx context.Context, updatedLink domain.LinkUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUpdate", ctx, updatedLink)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUpdate indicates an expected call of SendUpdate.
func (mr *MockNotifierMockRecorder) SendUpdate(ctx, updatedLink interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdate", reflect.TypeOf((*MockNotifier)(nil).SendUpdate), ctx, updatedLink)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockStorage) AddLink(chatID int64, URL string, tags []string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", chatID, URL, tags)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockStorageMockRecorder) AddLink(chatID, URL, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockStorage)(nil).AddLink), chatID, URL, tags)
}

// ChatExists mocks base method.
func (m *MockStorage) ChatExists(chatID int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatExists", chatID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ChatExists indicates an expected call of ChatExists.
func (mr *MockStorageMockRecorder) ChatExists(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatExists", reflect.TypeOf((*MockStorage)(nil).ChatExists), chatID)
}

// DeleteChat mocks base method.
func (m *MockStorage) DeleteChat(chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteChat", chatID)
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockStorageMockRecorder) DeleteChat(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockStorage)(nil).DeleteChat), chatID)
}

// GetAllLinks mocks base method.
func (m *MockStorage) GetAllLinks() []domain.Link {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinks")
	ret0, _ := ret[0].([]domain.Link)
	return ret0
}

// GetAllLinks indicates an expected call of GetAllLinks.
func (mr *MockStorageMockRecorder) GetAllLinks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinks", reflect.TypeOf((*MockStorage)(nil).GetAllLinks))
}

// GetLinks mocks base method.
func (m *MockStorage) GetLinks(chatID int64) []domain.Link {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", chatID)
	ret0, _ := ret[0].([]domain.Link)
	return ret0
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockStorageMockRecorder) GetLinks(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockStorage)(nil).GetLinks), chatID)
}

// GetSubscribers mocks base method.
func (m *MockStorage) GetSubscribers(url string) []int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribers", url)
	ret0, _ := ret[0].([]int64)
	return ret0
}

// GetSubscribers indicates an expected call of GetSubscribers.
func (mr *MockStorageMockRecorder) GetSubscribers(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribers", reflect.TypeOf((*MockStorage)(nil).GetSubscribers), url)
}

// RegisterChat mocks base method.
func (m *MockStorage) RegisterChat(chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterChat", chatID)
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockStorageMockRecorder) RegisterChat(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockStorage)(nil).RegisterChat), chatID)
}

// RemoveLink mocks base method.
func (m *MockStorage) RemoveLink(chatID int64, URL string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", chatID, URL)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockStorageMockRecorder) RemoveLink(chatID, URL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockStorage)(nil).RemoveLink), chatID, URL)
}

// UpdateTimestamp mocks base method.
func (m *MockStorage) UpdateTimestamp(url string, t time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateTimestamp", url, t)
}

// UpdateTimestamp indicates an expected call of UpdateTimestamp.
func (mr *MockStorageMockRecorder) UpdateTimestamp(url, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTimestamp", reflect.TypeOf((*MockStorage)(nil).UpdateTimestamp), url, t)
}
