// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/domain"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockClient) Check(ctx context.Context, link domain.Link) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, link)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockClientMockRecorder) Check(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockClient)(nil).Check), ctx, link)
}

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// SendUpdate mocks base method.
func (m *MockNotifier) SendUpdate(ctx context.Context, updatedLink domain.LinkUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUpdate", ctx, updatedLink)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUpdate indicates an expected call of SendUpdate.
func (mr *MockNotifierMockRecorder) SendUpdate(ctx, updatedLink interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdate", reflect.TypeOf((*MockNotifier)(nil).SendUpdate), ctx, updatedLink)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockStorage) AddLink(ctx context.Context, chatID int64, URL string, tags []string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, chatID, URL, tags)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockStorageMockRecorder) AddLink(ctx, chatID, URL, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockStorage)(nil).AddLink), ctx, chatID, URL, tags)
}

// ChatExists mocks base method.
func (m *MockStorage) ChatExists(ctx context.Context, chatID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatExists", ctx, chatID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatExists indicates an expected call of ChatExists.
func (mr *MockStorageMockRecorder) ChatExists(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatExists", reflect.TypeOf((*MockStorage)(nil).ChatExists), ctx, chatID)
}

// DeleteChat mocks base method.
func (m *MockStorage) DeleteChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockStorageMockRecorder) DeleteChat(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockStorage)(nil).DeleteChat), ctx, chatID)
}

// GetLinks mocks base method.
func (m *MockStorage) GetLinks(ctx context.Context, chatID int64, limit, offset int) ([]domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", ctx, chatID, limit, offset)
	ret0, _ := ret[0].([]domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockStorageMockRecorder) GetLinks(ctx, chatID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockStorage)(nil).GetLinks), ctx, chatID, limit, offset)
}

// GetLinksWithInterval mocks base method.
func (m *MockStorage) GetLinksWithInterval(ctx context.Context, limit, offset int, interval time.Duration) ([]domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinksWithInterval", ctx, limit, offset, interval)
	ret0, _ := ret[0].([]domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinksWithInterval indicates an expected call of GetLinksWithInterval.
func (mr *MockStorageMockRecorder) GetLinksWithInterval(ctx, limit, offset, interval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinksWithInterval", reflect.TypeOf((*MockStorage)(nil).GetLinksWithInterval), ctx, limit, offset, interval)
}

// GetSubscribers mocks base method.
func (m *MockStorage) GetSubscribers(ctx context.Context, url string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribers", ctx, url)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscribers indicates an expected call of GetSubscribers.
func (mr *MockStorageMockRecorder) GetSubscribers(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribers", reflect.TypeOf((*MockStorage)(nil).GetSubscribers), ctx, url)
}

// IsSubscribed mocks base method.
func (m *MockStorage) IsSubscribed(ctx context.Context, chatID int64, url string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSubscribed", ctx, chatID, url)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSubscribed indicates an expected call of IsSubscribed.
func (mr *MockStorageMockRecorder) IsSubscribed(ctx, chatID, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSubscribed", reflect.TypeOf((*MockStorage)(nil).IsSubscribed), ctx, chatID, url)
}

// RegisterChat mocks base method.
func (m *MockStorage) RegisterChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockStorageMockRecorder) RegisterChat(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockStorage)(nil).RegisterChat), ctx, chatID)
}

// RemoveLink mocks base method.
func (m *MockStorage) RemoveLink(ctx context.Context, chatID int64, URL string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", ctx, chatID, URL)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockStorageMockRecorder) RemoveLink(ctx, chatID, URL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockStorage)(nil).RemoveLink), ctx, chatID, URL)
}

// UpdateLastChecked mocks base method.
func (m *MockStorage) UpdateLastChecked(ctx context.Context, url string, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastChecked", ctx, url, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastChecked indicates an expected call of UpdateLastChecked.
func (mr *MockStorageMockRecorder) UpdateLastChecked(ctx, url, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastChecked", reflect.TypeOf((*MockStorage)(nil).UpdateLastChecked), ctx, url, t)
}

// UpdateTimestamp mocks base method.
func (m *MockStorage) UpdateTimestamp(ctx context.Context, url string, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTimestamp", ctx, url, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTimestamp indicates an expected call of UpdateTimestamp.
func (mr *MockStorageMockRecorder) UpdateTimestamp(ctx, url, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTimestamp", reflect.TypeOf((*MockStorage)(nil).UpdateTimestamp), ctx, url, t)
}
