// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package botserver is a generated GoMock package.
package botserver

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SendUpdates mocks base method.
func (m *MockService) SendUpdates(chatIds []int64, desc string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendUpdates", chatIds, desc)
}

// SendUpdates indicates an expected call of SendUpdates.
func (mr *MockServiceMockRecorder) SendUpdates(chatIds, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdates", reflect.TypeOf((*MockService)(nil).SendUpdates), chatIds, desc)
}
