// Code generated by MockGen. DO NOT EDIT.
// Source: internal/bot/infrastructure/receiver/kafka/consumer.go

// Package botkafka is a generated GoMock package.
package botkafka

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// HandleUpdate mocks base method.
func (m *MockService) HandleUpdate(chatIDs []int64, desc string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUpdate", chatIDs, desc)
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockServiceMockRecorder) HandleUpdate(chatIDs, desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockService)(nil).HandleUpdate), chatIDs, desc)
}
