// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package bot is a generated GoMock package.
package bot

import (
	reflect "reflect"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	gomock "github.com/golang/mock/gomock"
	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/bot/domain"
)

// MockTelegramAPI is a mock of TelegramAPI interface.
type MockTelegramAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramAPIMockRecorder
}

// MockTelegramAPIMockRecorder is the mock recorder for MockTelegramAPI.
type MockTelegramAPIMockRecorder struct {
	mock *MockTelegramAPI
}

// NewMockTelegramAPI creates a new mock instance.
func NewMockTelegramAPI(ctrl *gomock.Controller) *MockTelegramAPI {
	mock := &MockTelegramAPI{ctrl: ctrl}
	mock.recorder = &MockTelegramAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramAPI) EXPECT() *MockTelegramAPIMockRecorder {
	return m.recorder
}

// GetUpdatesChan mocks base method.
func (m *MockTelegramAPI) GetUpdatesChan(config tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatesChan", config)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// GetUpdatesChan indicates an expected call of GetUpdatesChan.
func (mr *MockTelegramAPIMockRecorder) GetUpdatesChan(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatesChan", reflect.TypeOf((*MockTelegramAPI)(nil).GetUpdatesChan), config)
}

// Self mocks base method.
func (m *MockTelegramAPI) Self() tgbotapi.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Self")
	ret0, _ := ret[0].(tgbotapi.User)
	return ret0
}

// Self indicates an expected call of Self.
func (mr *MockTelegramAPIMockRecorder) Self() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Self", reflect.TypeOf((*MockTelegramAPI)(nil).Self))
}

// Send mocks base method.
func (m *MockTelegramAPI) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", c)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockTelegramAPIMockRecorder) Send(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTelegramAPI)(nil).Send), c)
}

// SetCommands mocks base method.
func (m *MockTelegramAPI) SetCommands(cmds []domain.BotCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCommands", cmds)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCommands indicates an expected call of SetCommands.
func (mr *MockTelegramAPIMockRecorder) SetCommands(cmds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCommands", reflect.TypeOf((*MockTelegramAPI)(nil).SetCommands), cmds)
}

// StopReceivingUpdates mocks base method.
func (m *MockTelegramAPI) StopReceivingUpdates() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopReceivingUpdates")
}

// StopReceivingUpdates indicates an expected call of StopReceivingUpdates.
func (mr *MockTelegramAPIMockRecorder) StopReceivingUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopReceivingUpdates", reflect.TypeOf((*MockTelegramAPI)(nil).StopReceivingUpdates))
}

// MockCommandDispatcher is a mock of CommandDispatcher interface.
type MockCommandDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockCommandDispatcherMockRecorder
}

// MockCommandDispatcherMockRecorder is the mock recorder for MockCommandDispatcher.
type MockCommandDispatcherMockRecorder struct {
	mock *MockCommandDispatcher
}

// NewMockCommandDispatcher creates a new mock instance.
func NewMockCommandDispatcher(ctrl *gomock.Controller) *MockCommandDispatcher {
	mock := &MockCommandDispatcher{ctrl: ctrl}
	mock.recorder = &MockCommandDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandDispatcher) EXPECT() *MockCommandDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockCommandDispatcher) Dispatch(msg *domain.Message) (*domain.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", msg)
	ret0, _ := ret[0].(*domain.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockCommandDispatcherMockRecorder) Dispatch(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockCommandDispatcher)(nil).Dispatch), msg)
}

// GetCommands mocks base method.
func (m *MockCommandDispatcher) GetCommands() []domain.BotCommand {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommands")
	ret0, _ := ret[0].([]domain.BotCommand)
	return ret0
}

// GetCommands indicates an expected call of GetCommands.
func (mr *MockCommandDispatcherMockRecorder) GetCommands() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommands", reflect.TypeOf((*MockCommandDispatcher)(nil).GetCommands))
}
