// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package bot is a generated GoMock package.
package bot

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/bot/domain"
)

// MockCommandDispatcher is a mock of CommandDispatcher interface.
type MockCommandDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockCommandDispatcherMockRecorder
}

// MockCommandDispatcherMockRecorder is the mock recorder for MockCommandDispatcher.
type MockCommandDispatcherMockRecorder struct {
	mock *MockCommandDispatcher
}

// NewMockCommandDispatcher creates a new mock instance.
func NewMockCommandDispatcher(ctrl *gomock.Controller) *MockCommandDispatcher {
	mock := &MockCommandDispatcher{ctrl: ctrl}
	mock.recorder = &MockCommandDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandDispatcher) EXPECT() *MockCommandDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockCommandDispatcher) Dispatch(msg *domain.Message) (*domain.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", msg)
	ret0, _ := ret[0].(*domain.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockCommandDispatcherMockRecorder) Dispatch(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockCommandDispatcher)(nil).Dispatch), msg)
}

// GetCommands mocks base method.
func (m *MockCommandDispatcher) GetCommands() []domain.BotCommand {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommands")
	ret0, _ := ret[0].([]domain.BotCommand)
	return ret0
}

// GetCommands indicates an expected call of GetCommands.
func (mr *MockCommandDispatcherMockRecorder) GetCommands() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommands", reflect.TypeOf((*MockCommandDispatcher)(nil).GetCommands))
}
